### ISSUE TITLE
Could you release your trained model? I just run your code, but I just get 84% cls accuracy.

### ISSUE THREAD

**Issue by liruihui** [Yochengliu/Relation-Shape-CNN#10]

**Comment by ShiQiu0419** [comment]
> _No description provided._
I have got 92.2% with the default settings.
(P.S. your work on PU-GAN is excellent, thanks for sharing)

**Comment by liruihui** [comment]
> > _No description provided._
> > I have got 92.2% with the default settings.
> > (P.S. your work on PU-GAN is excellent, thanks for sharing)

Thanks. But the report accuracy is 93.6%, which makes a big improvement, compared with other methods. 92.2% is also not enough.

**Comment by lqzhao** [comment]
@liruihui 
![image](https://user-images.githubusercontent.com/43566465/65397795-96dfa800-dde5-11e9-9c9d-35298d5ec0c2.png)
Without voting and random scaling tricks, it achieves 92.2% acc.

**Comment by liruihui** [comment]
> @liruihui
> ![image](https://user-images.githubusercontent.com/43566465/65397795-96dfa800-dde5-11e9-9c9d-35298d5ec0c2.png)
> Without voting and random scaling tricks, it achieves 92.2% acc.

Thanks.

**Comment by Ailce8862** [comment]
> > > _No description provided._
> > > I have got 92.2% with the default settings.
> > > (P.S. your work on PU-GAN is excellent, thanks for sharing)
> 
> Thanks. But the report accuracy is 93.6%, which makes a big improvement, compared with other methods. 92.2% is also not enough.

Did you finally get the accuracy of the paper

**Comment by Ailce8862** [comment]
> @liruihui
> ![image](https://user-images.githubusercontent.com/43566465/65397795-96dfa800-dde5-11e9-9c9d-35298d5ec0c2.png)
> Without voting and random scaling tricks, it achieves 92.2% acc.

How do I get the accuracy of the paper

**Comment by Ailce8862** [comment]
> > _No description provided._
> > I have got 92.2% with the default settings.
> > (P.S. your work on PU-GAN is excellent, thanks for sharing)

Did you finally get the accuracy of the paper

**Comment by Ailce8862** [comment]
> > @liruihui
> > ![image](https://user-images.githubusercontent.com/43566465/65397795-96dfa800-dde5-11e9-9c9d-35298d5ec0c2.png)
> > Without voting and random scaling tricks, it achieves 92.2% acc.
> 
> Thanks.

Did you finally get the accuracy of the paper

**Comment by liruihui** [comment]
around 92%, but not stable.

Ruihui Li

**Comment by Ailce8862** [comment]
thanks


| |
梁攀
|
|
邮箱：liangxiaopan8862@126.com
|

签名由 网易邮箱大师 定制

On 01/04/2020 11:10, Li Ruihui wrote:

around 92%, but not stable.

Ruihui Li

**Comment by sheshap** [comment]
For SSG I got 92.71 as mentioned in the GitHub with voting. In the paper, the same has been mentioned as 92.2.

Anybody tried for msg please let us know the radii which you used.
