### ISSUE TITLE
compared with pointConv

### ISSUE THREAD

**Issue by weiweisun2018** [Yochengliu/Relation-Shape-CNN#11]
Hello authors,
Thanks a lot for releasing the code. The work is awesome!
For now, I am confused by difference pointConv in [PointConv: Deep Convolutional Networks on 3D Point Clouds](https://arxiv.org/pdf/1811.07246.pdf) and RSConv in your paper. For me, they look so similar. The main difference it the input of weight function. In RsConv, the input could be euclidean distance, normal, etc. In PointConv, the input could be the transition vector. Are the inputs significant? Could you please help to clarify that? It is appreciated.
Thanks!

**Comment by Yochengliu** [comment]
I think the original idea of all the similar works may be from [Dynamic Filter Networks](https://arxiv.org/abs/1605.09673). Intuitively, the input A to the Filter-generating network shoule be important for the target task. However, in point cloud processing field, the input A actually could only be a complementary cue that facilitates to shape capturing. Thus, the classification result is also good when we just use 3D Euclidean distance as the input A. 

In the paper, we in fact didn't explore the low-level relation fully and just use some intuitive/naive prior definitions to explore how it performs. That is, we are also not sure whether the result would be better if using some advanced relations or just combining the learned high-level features like [DGCNN](https://arxiv.org/abs/1801.07829).

**Comment by weiweisun2018** [comment]
Thank you so much for your reply.  It clearly answers my question. Indeed, the relation could be a very important cue to the point-CONV. 
I think I could close this issue. Really appreciate your answer! :)
