### ISSUE TITLE
when will you release the code about semantic part segmetation?

### ISSUE THREAD

**Issue by longmalongma** [Yochengliu/Relation-Shape-CNN#12]
Hello,thank you for our work.I want to know when will you release the code about semantic part segmentation?looking for your reply.

**Comment by Yochengliu** [comment]
Hi, sorry for the late response.
We have released the code of shape part segmentation, please have a check.

**Comment by longmalongma** [comment]
thank you for your reply。how nice woek it is！





------------------ Original ------------------

**Comment by zhangxuliqiang** [comment]
Dear author, i met a KeyError when i run your part_seg code, KeyError: tensor(22); after only one epoch the error occured. How can i deal with it?

**Comment by Yochengliu** [comment]
@zhangxuliqiang   File "train_partseg.py", line 172, in validate, cat = seg_label_to_cat[target[b, 0]]
For pytorch 0.4.*, maybe you need to convert the tensor target[b, 0] to numpy, try target[b, 0].numpy()

**Comment by Yochengliu** [comment]
Close the issue, feel free to raise again.

**Comment by Anniessq** [comment]
> 
> 
> @zhangxuliqiang File "train_partseg.py", line 172, in validate, cat = seg_label_to_cat[target[b, 0]]
> For pytorch 0.4.*, maybe you need to convert the tensor target[b, 0] to numpy, try target[b, 0].numpy()

I have tried the method you offer,but, I met TypeError:unhashable type:'numpy.ndarray' when it trained less than one epoch,waiting for your rely,thank you!

**Comment by Yochengliu** [comment]
@Anniessq  Please try  target[b, 0].numpy()[0]

If not work, you may have a try yourself. The key is just to convert the datatype 'tensor(22)' in pytorch 0.4.* to an integer that can access the dictionary 'seg_label_to_cat'.
