### ISSUE TITLE
How  about the visualization?

### ISSUE THREAD

**Issue by limt15** [Yochengliu/Relation-Shape-CNN#14]
Dear author, thank you very much for sharing the classification code.

I am wondering about the visualization about the results of the segmentation experiments, Could you please share the code of the visualization?

Waiting for your reply~

**Comment by Yochengliu** [comment]
Hi, we use the matlab tool: https://www.geo.tuwien.ac.at/downloads/pg/pctools/pctools.html 
you can also use CloudCompare or MeshLab.

**Comment by Yochengliu** [comment]
Sorry for closing this issue, please feel free to raise again.

**Comment by longmalongma** [comment]
> Sorry for closing this issue, please feel free to raise again.



> Sorry for closing this issue, please feel free to raise again.

how to visualize the results of part segmentation?i do not find you save obj or off files.

**Comment by XUJIALIOSWALD** [comment]
> > 很抱歉关闭此问题，请随时提出。
> 
> > 很抱歉关闭此问题，请随时提出。
> 
> 如何可视化零件细分的结果？我找不到保存obj或关闭文件的方法。



> > Sorry for closing this issue, please feel free to raise again.
> 
> > Sorry for closing this issue, please feel free to raise again.
> 
> how to visualize the results of part segmentation?i do not find you save obj or off files.

Excuse me, have you solved this problem?

**Comment by XUJIALIOSWALD** [comment]
> > Sorry for closing this issue, please feel free to raise again.
> 
> > Sorry for closing this issue, please feel free to raise again.
> 
> how to visualize the results of part segmentation?i do not find you save obj or off files.

Excuse me, have you solved this problem?

**Comment by XJLXuJiaLi** [comment]
> > Sorry for closing this issue, please feel free to raise again.
> 
> > Sorry for closing this issue, please feel free to raise again.
> 
> how to visualize the results of part segmentation?i do not find you save obj or off files.

Hello, have you solved this problem?
