### ISSUE TITLE
RuntimeError: no deterministic convolution algorithms available in CuDNN

### ISSUE THREAD

**Issue by TheJasal** [Yochengliu/Relation-Shape-CNN#24]
This one：
        h_xi_xj = self.mapping_func2(self.activation(self.bn_mapping(self.mapping_func1(h_xi_xj))))
cause ：

RuntimeError: no deterministic convolution algorithms available in CuDNN

**Comment by Colin97** [comment]
how did you solve that? @TheJasal

**Comment by TheJasal** [comment]
@Colin97 Pytorch 0.3, CMake > 2.8, CUDA 8.0 + cuDNN 5.1
