### ISSUE TITLE
Confused about the symmetric aggregation function

### ISSUE THREAD

**Issue by Fresh-Z** [Yochengliu/Relation-Shape-CNN#3]
dear author, RS-CNN is excellent! but I am confused about the aggregation function, which you said it's symmetric, such as summation or max pooling, in Session 4.3, Figure 8, in the 1st layer, there are 512 points(1/2 of the input points), but in the 2nd layer, there remain only 128 points(1/4 of the 1st layer),  why? the relation-shape convolution(implemented as shared MLP) and channel-raising mapping(also shared MLP) don't seem to change the point number, because of the aggregation function? how?
Thank you! Looking forward to your reply!

**Comment by Yochengliu** [comment]
Sorry for confusion. The change of points' number is achieved by sampling. You can sample 512 points from the input 1024 points, and then take the 128 points as the local centroids x_i to construct local point subsets N(x_i) for "convolution". Please refer to the 2nd part in Sec 3.5 and Fig. 4(b). If it is still difficult for you to understand this part, you can refer to the codes of PointNet++, or wait for our codes.

**Comment by Fresh-Z** [comment]
Oh! Thank you! I think I understand now.

**Comment by Fresh-Z** [comment]
Oh! Thank you! I think I understand now!
