### ISSUE TITLE
forward function in PointNetSAModuleMSG 

### ISSUE THREAD

**Issue by yash1112** [Yochengliu/Relation-Shape-CNN#41]
Hi, 
Great work!
Your approach to 3d shape classification problem is quite unique.
I was trying to understand your code I am confused as there is no forward function in PointNetSAModuleMSG. So when in rscnn_cls the PointNetSA  MSG module is called with data where does it actually point in pointnet2_modules.py and how does it furthers passes data to rsconv function in pointnet2_utils.
Thanks!!

**Comment by Yochengliu** [comment]
Hi, thanks for your interest.
The issue you raised could be a confusion of Python language. I guess you must fix this issue when knowing about Python better :) Also, you may need to check the code structure more carefully. It is in fact easy for understanding.
Have a nice experience of Python!
