### ISSUE TITLE
Visualization of segmentation results for Shapenet Part

### ISSUE THREAD

**Issue by zero-zm** [Yochengliu/Relation-Shape-CNN#43]
I used the code you provided to conduct the experiment on the Shapenet Part dataset and could get the MIOU value, but I could not get the visualization result. So I would like to ask you how to do it.
Looking forward to your reply. Thank you

**Comment by Yochengliu** [comment]
You can use MeshLab or Cloudcompare for visualization. Both of them are very easy to use.

**Comment by zero-zm** [comment]
Received, thank you

---Original---
From: "Yongcheng ***@***.***&gt;
Date: Mon, Feb 14, 2022 17:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Yochengliu/Relation-Shape-CNN] Visualization of segmentationresults for Shapenet Part (#43)




 
You can use MeshLab or Cloudcompare for visualization. Both of them are very easy to use.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
