### ISSUE TITLE
How to get-93.6% accuracy? 

### ISSUE THREAD

**Issue by merazlab** [Yochengliu/Relation-Shape-CNN#44]
First Thank You for this contribution.
I run your code without any changes, but not getting 93.6% accuracy which is mention in your paper. I am only getting 92.18% accuracy. Guide me How to get 93.6% accuracy.

**Comment by imankgoyal** [comment]
Hi, this is because of the multi scale version is not released yet. You might find our repo https://github.com/princeton-vl/SimpleView to be useful.

**Comment by merazlab** [comment]
thanks @imankgoyal
