### ISSUE TITLE
Inference time?

### ISSUE THREAD

**Issue by niallomahony93** [Yochengliu/Relation-Shape-CNN#5]
Can you give an idea of what length of time is required for inference? Also, do you plan to share the code on GitHub?

**Comment by Yochengliu** [comment]
Hi, I'm very sorry for the delay. Code has been released, please have a test.

**Comment by niallomahony93** [comment]
Thank you, your paper is very interesting I look forward to testing it.

**Comment by Yochengliu** [comment]
Sorry for closing this issue, please feel free to raise again.
