### ISSUE TITLE
Will this also work for Paris Lille Dataset?

### ISSUE THREAD

**Issue by Sajjadmanal** [Yochengliu/Relation-Shape-CNN#6]
Hi,
This is an amazing research on Point Cloud Segmentation. I wish to know if it will also work for [Paris Lille](http://npm3d.fr/paris-lille-3d) Dataset or [Semantic3d ](http://www.semantic3d.net/view_dbase.php?chl=1#download)Dataset too?

**Comment by Yochengliu** [comment]
Hi, thanks.
Ur...I'm not sure honestly...maybe you can have a try :)

**Comment by Yochengliu** [comment]
Sorry for closing this issue, please feel free to raise again.
