### ISSUE TITLE
how to apply this structure to semantic segmentation

### ISSUE THREAD

**Issue by flyflyfly0120** [Yochengliu/Relation-Shape-CNN#64]
hi, thanks for your release code and i learned a lot from it. now i have some question,that how can i use this RS-CNN to sovle the problem of semantic segmentation?
can the part-seg code also use in semantic seg ?
im sorry to bother you.thanks

**Comment by Yochengliu** [comment]
Thanks for your interest. 
[can the part-seg code also use in semantic seg ?]
Yes, but you need to modify some codes, such as the setting of [radii, nsamples] and self.FC_layer in rscnn_msn_seg.py for adapting to your segmentation task. Of course, you should also modify the dataload codes and training codes for specifically processing your task.
Have a nice try!
