### ISSUE TITLE
请问prior relation在哪个代码文件中进行计算？

### ISSUE THREAD

**Issue by yuanlinwang** [Yochengliu/Relation-Shape-CNN#68]
我看了各个文件的代码，但没有找到 10维的数据输入的计算过程，在trian文件中，只是先读了数据，然后将数据放入model中，可是初始数据只有3维，生成10维输入的相应代码在哪个文件中呢？期待您的回复！

**Comment by Yochengliu** [comment]
感谢关注！
https://github.com/Yochengliu/Relation-Shape-CNN/blob/master/utils/pytorch_utils/pytorch_utils.py
Line60-64

**Comment by yuanlinwang** [comment]
@Yochengliu 非常感谢您的回复！
