### ISSUE TITLE
about release the code for segmentation task

### ISSUE THREAD

**Issue by amiltonwong** [Yochengliu/Relation-Shape-CNN#9]
Hi, @Yochengliu ,

Thanks for releasing your code. However, it currently contains only code for modelnet40 classificaton task. Would you also release the code for segmentation task?

THX!

**Comment by Yochengliu** [comment]
Hi, sorry for the late response.
We have released the code of shape part segmentation, please have a check.

**Comment by Yochengliu** [comment]
Close this issue, feel free to raise again.
